language: node_js
node_js:
  - 14

before_install:
  - 'npm i -g firebase-tools'

script:
  - echo "skipped tests"

deploy:
  provider: firebase
  token:
    secure: 'JL7vsIdyZXOwV/60wMTqdyH13+eYIaTCOHawXOc9xejl+s+mVM2eaiqnsMZmb0D1jjgbGU5l/DnyvAYtPFCpUlwE0P7X7SFkvdEWuuvQLItW7uC7MitJuxBUu3bYYbUp+etzubFBaPul/xaeo561owQ5c/MuSOcdgEvOHmw03BVDLLrS94dyzgPEMt8av4Zeq0P8vuEtVXWgVy8T2odowcUBOwtM/+Yvf8bT3FRCM7Efeym0HEkdiezuZZl+lCNCL2cTQ70CvT6bufNOx3IpSjoOG+w4FJ2jGsNOgRW70IFaRc7l5KPZ5UVkDGz+qQn+nozSiNrTGrLOW21cvpCsxXhosGNL51hOFDL6Tag/oEQnK9McnGFaKyF8MYvUjvJhFwO26wdqR1EFI5hgHWL6zuAD1Rv+hTTS3mJBu/6W4wgBXvYT1n6MS68gEelnBzBVZTBK6ofj+rHs3G7n9kNk9eWt2Ab6SQK/P8AKoZcTzgJb8ZfMfpE5oeEgRV8yiOBpz5bohpYPosalY6hQsyC5yAL5HAjNZJ8cdBWoVqr620fpk/AhrA4QP05EIZhB9TGD4CAvCdxkJMzQc1YxpzL/R9WdZS7r4XxCkZz2RXnnuIUsVNVxlYrsrejgvSBE8LA4VGcHmFzH74CMJKjsDmZ8/uhXV9LavH+cqbIGGNGLYf0='
